matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9.4
      script:
        - set -o pipefail
        - xcodebuild test -scheme EasyImagy-macOS -configuration Debug | xcpretty -c
        - xcodebuild test -scheme EasyImagy-iOS -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone X" | xcpretty -c
        - xcodebuild test -scheme EasyImagy-tvOS -configuration Debug -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 4K" | xcpretty -c
        - xcodebuild build -scheme EasyImagy-watchOS -configuration Debug -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch Series 3 - 38mm" | xcpretty -c
        - xcodebuild test -scheme EasyImagy-macOS -configuration Release | xcpretty -c
        - xcodebuild test -scheme EasyImagy-iOS -configuration Release -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone X" | xcpretty -c
        - xcodebuild test -scheme EasyImagy-tvOS -configuration Release -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 4K" | xcpretty -c
        - xcodebuild build -scheme EasyImagy-watchOS -configuration Release -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch Series 3 - 38mm" | xcpretty -c
    - os: osx
      language: objective-c
      osx_image: xcode10
      script:
        - set -o pipefail
        - xcodebuild test -scheme EasyImagy-macOS -configuration Debug | xcpretty -c
        - xcodebuild test -scheme EasyImagy-iOS -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone XS" | xcpretty -c
        - xcodebuild test -scheme EasyImagy-tvOS -configuration Debug -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 4K" | xcpretty -c
        - xcodebuild build -scheme EasyImagy-watchOS -configuration Debug -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch Series 4 - 44mm" | xcpretty -c
        - xcodebuild test -scheme EasyImagy-macOS -configuration Release | xcpretty -c
        - xcodebuild test -scheme EasyImagy-iOS -configuration Release -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone XS" | xcpretty -c
        - xcodebuild test -scheme EasyImagy-tvOS -configuration Release -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 4K" | xcpretty -c
        - xcodebuild build -scheme EasyImagy-watchOS -configuration Release -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch Series 4 - 44mm" | xcpretty -c
    - os: osx
      language: objective-c
      osx_image: xcode10.2
      script:
        - set -o pipefail
        - xcodebuild test -scheme EasyImagy-macOS -configuration Debug | xcpretty -c
        - xcodebuild test -scheme EasyImagy-iOS -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone XS" | xcpretty -c
        - xcodebuild test -scheme EasyImagy-tvOS -configuration Debug -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 4K" | xcpretty -c
        - xcodebuild build -scheme EasyImagy-watchOS -configuration Debug -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch Series 4 - 44mm" | xcpretty -c
        - xcodebuild test -scheme EasyImagy-macOS -configuration Release | xcpretty -c
        - xcodebuild test -scheme EasyImagy-iOS -configuration Release -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone XS" | xcpretty -c
        - xcodebuild test -scheme EasyImagy-tvOS -configuration Release -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 4K" | xcpretty -c
        - xcodebuild build -scheme EasyImagy-watchOS -configuration Release -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch Series 4 - 44mm" | xcpretty -c
    - os: osx
      language: generic
      osx_image: xcode9.4
      script:
        - swift --version
        - swift build
        - swift test
        - swift build -c release
        - swift test -c release
    - os: osx
      language: generic
      osx_image: xcode10
      script:
        - swift --version
        - swift build
        - swift test
        - swift build -c release
        - swift test -c release
    - os: osx
      language: generic
      osx_image: xcode10.2
      script:
        - swift --version
        - swift build
        - swift test
        - swift build -c release
        - swift test -c release
    - os: linux
      language: generic
      sudo: required
      env: SWIFT_VERSION=4.1
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - swift --version
        - swift build
        - swift test
        - swift build -c release
        - swift test -c release
    - os: linux
      language: generic
      sudo: required
      env: SWIFT_VERSION=4.2
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - swift --version
        - swift build
        - swift test
        - swift build -c release
        - swift test -c release
    - os: linux
      language: generic
      sudo: required
      env: SWIFT_VERSION=5.0
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - swift --version
        - swift build
        - swift test
        - swift build -c release
        - swift test -c release
